export type IdxTicker = { symbol: string; name: string }

export const IDX_TICKERS: IdxTicker[] = [
  { symbol: "BBCA.JK", name: "Bank Central Asia Tbk" },
  { symbol: "BBRI.JK", name: "Bank Rakyat Indonesia Tbk" },
  { symbol: "BMRI.JK", name: "Bank Mandiri Tbk" },
  { symbol: "TLKM.JK", name: "Telkom Indonesia Tbk" },
  { symbol: "ASII.JK", name: "Astra International Tbk" },
  { symbol: "UNVR.JK", name: "Unilever Indonesia Tbk" },
  { symbol: "ICBP.JK", name: "Indofood CBP Sukses Makmur Tbk" },
  { symbol: "INDF.JK", name: "Indofood Sukses Makmur Tbk" },
  { symbol: "ADRO.JK", name: "Adaro Energy Indonesia Tbk" },
  { symbol: "ANTM.JK", name: "Aneka Tambang Tbk" },
  { symbol: "PTBA.JK", name: "Bukit Asam Tbk" },
  { symbol: "KLBF.JK", name: "Kalbe Farma Tbk" },
  { symbol: "SMGR.JK", name: "Semen Indonesia Tbk" },
  { symbol: "GGRM.JK", name: "Gudang Garam Tbk" },
  { symbol: "HMSP.JK", name: "HM Sampoerna Tbk" },
  { symbol: "JSMR.JK", name: "Jasa Marga Tbk" },
  { symbol: "PGAS.JK", name: "Perusahaan Gas Negara Tbk" },
  { symbol: "INKP.JK", name: "Indah Kiat Pulp & Paper Tbk" },
  { symbol: "TKIM.JK", name: "Pabrik Kertas Tjiwi Kimia Tbk" },
  { symbol: "BRIS.JK", name: "Bank Syariah Indonesia Tbk" },
  { symbol: "ARTO.JK", name: "Bank Jago Tbk" },
  { symbol: "GOTO.JK", name: "GoTo Gojek Tokopedia Tbk" },
  { symbol: "BUKA.JK", name: "Bukalapak.com Tbk" },
  { symbol: "EMTK.JK", name: "Elang Mahkota Teknologi Tbk" },
  { symbol: "MAPI.JK", name: "Mitra Adiperkasa Tbk" },
  { symbol: "ERAA.JK", name: "Erajaya Swasembada Tbk" },
  { symbol: "CPIN.JK", name: "Charoen Pokphand Indonesia Tbk" },
  { symbol: "JPFA.JK", name: "Japfa Comfeed Indonesia Tbk" },
  { symbol: "INCO.JK", name: "Vale Indonesia Tbk" },
  { symbol: "MDKA.JK", name: "Merdeka Copper Gold Tbk" },
  { symbol: "AMRT.JK", name: "Sumber Alfaria Trijaya Tbk" },
  { symbol: "MYOR.JK", name: "Mayora Indah Tbk" },
  { symbol: "HRUM.JK", name: "Harum Energy Tbk" },
  { symbol: "PTPP.JK", name: "PP (Persero) Tbk" },
  { symbol: "WIKA.JK", name: "Wijaya Karya Tbk" },
  { symbol: "WSKT.JK", name: "Waskita Karya Tbk" },
  { symbol: "BSDE.JK", name: "Bumi Serpong Damai Tbk" },
  { symbol: "CTRA.JK", name: "Ciputra Development Tbk" },
  { symbol: "PWON.JK", name: "Pakuwon Jati Tbk" },
  { symbol: "BBNI.JK", name: "Bank Negara Indonesia Tbk" },
  { symbol: "BBTN.JK", name: "Bank Tabungan Negara Tbk" },
  { symbol: "BNGA.JK", name: "Bank CIMB Niaga Tbk" },
  { symbol: "BDMN.JK", name: "Bank Danamon Indonesia Tbk" },
  { symbol: "BNLI.JK", name: "Bank Permata Tbk" },
  { symbol: "MEGA.JK", name: "Bank Mega Tbk" },
  { symbol: "NISP.JK", name: "Bank OCBC NISP Tbk" },
  { symbol: "PNBN.JK", name: "Bank Pan Indonesia Tbk" },
  { symbol: "ISAT.JK", name: "Indosat Tbk" },
  { symbol: "EXCL.JK", name: "XL Axiata Tbk" },
  { symbol: "FREN.JK", name: "Smartfren Telecom Tbk" },
  { symbol: "TOWR.JK", name: "Sarana Menara Nusantara Tbk" },
  { symbol: "TBIG.JK", name: "Tower Bersama Infrastructure Tbk" },
  { symbol: "AKRA.JK", name: "AKR Corporindo Tbk" },
  { symbol: "SCMA.JK", name: "Surya Citra Media Tbk" },
  { symbol: "MNCN.JK", name: "Media Nusantara Citra Tbk" },
  { symbol: "FILM.JK", name: "MD Pictures Tbk" },
  { symbol: "INTP.JK", name: "Indocement Tunggal Prakarsa Tbk" },
  { symbol: "SMCB.JK", name: "Solusi Bangun Indonesia Tbk" },
  { symbol: "WTON.JK", name: "Wijaya Karya Beton Tbk" },
  { symbol: "WOOD.JK", name: "Integra Indocabinet Tbk" },
  { symbol: "ULTJ.JK", name: "Ultra Jaya Milk Industry Tbk" },
  { symbol: "SIDO.JK", name: "Industri Jamu Sido Muncul Tbk" },
  { symbol: "HEAL.JK", name: "Medikaloka Hermina Tbk" },
  { symbol: "MIKA.JK", name: "Mitra Keluarga Karyasehat Tbk" },
  { symbol: "SILO.JK", name: "Siloam International Hospitals Tbk" },
  { symbol: "KINO.JK", name: "Kino Indonesia Tbk" },
  { symbol: "LSIP.JK", name: "PP London Sumatra Indonesia Tbk" },
  { symbol: "AALI.JK", name: "Astra Agro Lestari Tbk" },
  { symbol: "SIMP.JK", name: "Salim Ivomas Pratama Tbk" },
  { symbol: "SSMS.JK", name: "Sawit Sumbermas Sarana Tbk" },
  { symbol: "ITMG.JK", name: "Indo Tambangraya Megah Tbk" },
  { symbol: "BUMI.JK", name: "Bumi Resources Tbk" },
  { symbol: "KKGI.JK", name: "Resource Alam Indonesia Tbk" },
  { symbol: "TINS.JK", name: "Timah Tbk" },
  { symbol: "MEDC.JK", name: "Medco Energi Internasional Tbk" },
  { symbol: "ELSA.JK", name: "Elnusa Tbk" },
  { symbol: "RALS.JK", name: "Ramayana Lestari Sentosa Tbk" },
  { symbol: "ACES.JK", name: "Ace Hardware Indonesia Tbk" },
  { symbol: "HERO.JK", name: "Hero Supermarket Tbk" },
  { symbol: "LPPF.JK", name: "Matahari Department Store Tbk" },
  { symbol: "MLPL.JK", name: "Multipolar Tbk" },
  { symbol: "MPMX.JK", name: "Mitra Pinasthika Mustika Tbk" },
  { symbol: "BIRD.JK", name: "Blue Bird Tbk" },
  { symbol: "GIAA.JK", name: "Garuda Indonesia Tbk" },
  { symbol: "SMDR.JK", name: "Samudera Indonesia Tbk" },
  { symbol: "TMAS.JK", name: "Pelayaran Tempuran Emas Tbk" },
  { symbol: "ASSA.JK", name: "Adi Sarana Armada Tbk" },
  { symbol: "ROTI.JK", name: "Nippon Indosari Corpindo Tbk" },
  { symbol: "DLTA.JK", name: "Delta Djakarta Tbk" },
  { symbol: "MLBI.JK", name: "Multi Bintang Indonesia Tbk" },
  { symbol: "GJTL.JK", name: "Gajah Tunggal Tbk" },
  { symbol: "AUTO.JK", name: "Astra Otoparts Tbk" },
  { symbol: "SMSM.JK", name: "Selamat Sempurna Tbk" },
  { symbol: "RAJA.JK", name: "Rukun Raharja Tbk" },
  { symbol: "INET.JK", name: "Indoritel Makmur Internasional Tbk" },
  { symbol: "KREN.JK", name: "Kresna Graha Investama Tbk" },
]
